config/routes.rb
MyPortfolio::Application.routes.draw do

  devise_for :users, path_names: { sign_in: "login",
                                   sign_out: "logout" },
                    controllers: { omniauth_callbacks: "omniauth_callbacks",
                                   sessions: "sessions" }

  resources :posts do
    resources :comments
  end

  resources :projects do
    resources :comments
  end

  resources :users

  root :to => 'about#index'

  get 'login' => 'devise/sessions#new'
  get 'about_me' => 'about#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<head>
  <%= stylesheet_link_tag "home", :media => "all" %>
</head>
<body>
  <div class="body-home">
    <div class="landingtitle">
      <div class="home">DylanGrant.us</div>
    </div>
    <div class="flex-box">
      <div class="me">
        <%= link_to image_tag("https://s3-us-west-2.amazonaws.com/dylangrant.us/landing_page/dylan_zen_200.png", :border => 0), about_me_path, title: "About Me" %>
      </div>
      <div class="port">
        <%= link_to image_tag("https://s3-us-west-2.amazonaws.com/dylangrant.us/landing_page/grubly_landing_page_200.png", :border => 0), projects_path, title: "My Projects" %>
      </div>
      <div class="blog">
        <%= link_to image_tag("https://s3-us-west-2.amazonaws.com/dylangrant.us/landing_page/blog_200.png", :border => 0), posts_path, title: "Bloggin'" %>
      </div>
    </div>
  </div>
</body>
<!--

  <div class="teamblock whiteblock block">
      <div id="team" class="block-container">
          <h2 class="title">CHANGE ME</h2>
          <div class="description">CHANGE ME</div>
          <div class="teamcontainer">
              <div class="personal">
                  <div class="photo">
                      <img src="img/team/director.png">
                  </div>
                  <div class="userinfo">
                      <div class="name">CHANGE ME</div>
                      <div class="status">CHANGE ME</div>
                      <div class="socialblock">
                          <a href="#" title="Facebook" class="socialicon"><i class="icon-facebook-sign"></i></a>
                          <a href="#" title="Twitter" class="socialicon"><i class="icon-twitter-sign"></i></a>
                          <a href="#" title="Google Plus" class="socialicon"><i class="icon-google-plus-sign"></i></a>
                      </div>
                  </div>
              </div>

              <div class="personal">
                  <div class="photo">
                      <img src="img/team/designer.png">
                  </div>
                  <div class="userinfo">
                      <div class="name">CHANGE ME</div>
                      <div class="status">CHANGE ME</div>
                      <div class="socialblock">
                          <a href="#" title="Facebook" class="socialicon"><i class="icon-facebook-sign"></i></a>
                          <a href="#" title="Twitter" class="socialicon"><i class="icon-twitter-sign"></i></a>
                          <a href="#" title="Dribbble" class="socialicon"><i class="icon-dribbble"></i></a>
                          <a href="#" title="Google Plus" class="socialicon"><i class="icon-google-plus-sign"></i></a>
                      </div>
                  </div>
              </div>

              <div class="personal">
                  <div class="photo">
                      <img src="img/team/developer.png">
                  </div>
                  <div class="userinfo">
                      <div class="name">CHANGE ME</div>
                      <div class="status">CHANGE ME</div>
                      <div class="socialblock">
                          <a href="#" title="Facebook" class="socialicon"><i class="icon-facebook-sign"></i></a>
                          <a href="#" title="Twitter" class="socialicon"><i class="icon-twitter-sign"></i></a>
                          <a href="#" title="Google Plus" class="socialicon"><i class="icon-google-plus-sign"></i></a>
                          <a href="#" title="GitHub" class="socialicon"><i class="icon-github"></i></a>
                      </div>
                  </div>
              </div>

              <div class="personal">
                  <div class="photo">
                      <img src="img/team/seo.png">
                  </div>
                  <div class="userinfo">
                      <div class="name">CHANGE ME</div>
                      <div class="status">CHANGE ME</div>
                      <div class="socialblock">
                          <a href="#" title="Facebook" class="socialicon"><i class="icon-facebook-sign"></i></a>
                          <a href="#" title="Twitter" class="socialicon"><i class="icon-twitter-sign"></i></a>
                          <a href="#" title="Google Plus" class="socialicon"><i class="icon-google-plus-sign"></i></a>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>

  <div class="colorblock block priceblock">
      <div id="price" class="block-container">

          <h2 class="title">CHANGE ME</h2>
          <div class="description">CHANGE ME</div>
          <div class="pricetable">
              <div class="priceitem bronze">
                  <div class="wrapper">
                      <h3 class="title">CHANGE ME</h3>
                      <div class="services-list">
                          <div class="service include">
                              <i class="icon-ok-sign"></i>
                              <span>Admin panel</span>
                          </div>
                          <div class="service exclude">
                              <i class="icon-remove-sign"></i>
                              <span>Unlimited space</span>
                          </div>
                          <div class="service exclude">
                              <i class="icon-remove-sign"></i>
                              <span>Personal design</span>
                          </div>
                          <div class="service exclude">
                              <i class="icon-remove-sign"></i>
                              <span>24/7 Support</span>
                          </div>
                      </div>
                      <div class="cost">
                          <div class="container">
                              <h1>$9</h1>
                              <span class="line">/month</span>
                          </div>
                      </div>
                      <a href="#" class="button">CHANGE ME</a>
                  </div>
              </div>

              <div class="priceitem silver">
                  <div class="wrapper">
                      <h3 class="title">CHANGE ME</h3>
                      <div class="services-list">
                          <div class="service include">
                              <i class="icon-ok-sign"></i>
                              <span>Admin panel</span>
                          </div>
                          <div class="service include">
                              <i class="icon-ok-sign"></i>
                              <span>Unlimited space</span>
                          </div>
                          <div class="service exclude">
                              <i class="icon-remove-sign"></i>
                              <span>Personal design</span>
                          </div>
                          <div class="service exclude">
                              <i class="icon-remove-sign"></i>
                              <span>24/7 Support</span>
                          </div>
                      </div>
                      <div class="cost">
                          <div class="container">
                              <h1>$19</h1>
                              <span class="line">/month</span>
                          </div>
                      </div>
                      <a href="#" class="button">CHANGE ME</a>
                  </div>
              </div>

              <div class="priceitem gold">
                  <div class="wrapper">
                      <h3 class="title">CHANGE ME</h3>
                      <div class="services-list">
                          <div class="service include">
                              <i class="icon-ok-sign"></i>
                              <span>Admin panel</span>
                          </div>
                          <div class="service include">
                              <i class="icon-ok-sign"></i>
                              <span>Unlimited space</span>
                          </div>
                          <div class="service include">
                              <i class="icon-ok-sign"></i>
                              <span>Personal design</span>
                          </div>
                          <div class="service exclude">
                              <i class="icon-remove-sign"></i>
                              <span>24/7 Support</span>
                          </div>
                      </div>
                      <div class="cost">
                          <div class="container">
                              <h1>$29</h1>
                              <span class="line">/month</span>
                          </div>
                      </div>
                      <a href="#" class="button">CHANGE ME</a>
                  </div>
              </div>

              <div class="priceitem diamond">
                  <div class="wrapper">
                      <h3 class="title">CHANGE ME</h3>
                      <div class="services-list">
                          <div class="service include">
                              <i class="icon-ok-sign"></i>
                              <span>Admin panel</span>
                          </div>
                          <div class="service include">
                              <i class="icon-ok-sign"></i>
                              <span>Unlimited space</span>
                          </div>
                          <div class="service include">
                              <i class="icon-ok-sign"></i>
                              <span>Personal design</span>
                          </div>
                          <div class="service include">
                              <i class="icon-ok-sign"></i>
                              <span>24/7 Support</span>
                          </div>
                      </div>
                      <div class="cost">
                          <div class="container">
                              <h1>$39</h1>
                              <span class="line">/month</span>
                          </div>
                      </div>
                      <a href="#" class="button">CHANGE ME</a>
                  </div>
              </div>
          </div>

          <div class="infoblock">
              <h3 class="title">CHANGE ME</h3>
              <div class="subscription">
                  CHANGE ME
              </div>
              <div class="contacticons">
                  <div class="item">
                      <i class="icon-phone"></i>
                      <span class="sign">CHANGE ME</span>
                  </div>

                  <a href="#" class="item">
                      <i class="icon-envelope"></i>
                      <span class="sign">CHANGE ME</span>
                  </a>

                  <a href="#" class="item">
                      <i class="icon-skype"></i>
                      <span class="sign">CHANGE ME</span>
                  </a>
              </div>
          </div>
      </div>
  </div>
 -->