config/routes.rb
MyPortfolio::Application.routes.draw do

  devise_for :users, path_names: { sign_in: "login",
                                   sign_out: "logout" },
                    controllers: { omniauth_callbacks: "omniauth_callbacks",
                                   sessions: "sessions" }

  resources :posts do
    resources :comments
  end

  resources :projects do
    resources :comments
  end

  resources :users

  root :to => 'about#index'

  get 'login' => 'devise/sessions#new'
  get 'about_me' => 'about#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name,
                  :tech_used,
                  :description,
                  :http_link,
                  :published,
                  :content,
                  :image,
                  :remote_image_url,
                  :image_processed

  belongs_to :author, class_name: "User"

  mount_uploader :image, ImageUploader

  has_many :comments, as: :commentable

  after_save :enqueue_image

  def publish!
    published = true
    save!
  end

  def image_name
    File.basename(image.path || image.filename) if image
  end

  def enqueue_image
    ImageWorker.perform_async(id, key) if key.present?
  end

  class ImageWorker
    include Sidekiq::Worker

    def perform(id, key)
      project = Project.find(id)
      project.key = key
      project.remote_image_url = project.image.direct_fog_url(with_path: true)
      project.save!
      project.update_column(:image_processed, true)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  def index
    @projects = policy_scope(Project) #Project.all
    @uploader = Project.new.image
    @uploader.success_action_redirect = new_project_url

    respond_to do |format|
      format.html
      format.json { render json: @projects }
    end
  end

  def show
    @project = Project.find(params[:id])
    @commentable = @project
    @comments = @commentable.comments
    @comment = Comment.new
    authorize @project

    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
  end

  def new
    @project = Project.new(key: params[:key])

    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
  end

  def edit
    @project = Project.find(params[:id])
    authorize @project
  end

  def create
    @project = Project.new(params[:project])
    authorize @project

    respond_to do |format|

      if @project.save
        format.html { redirect_to @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
   @project = Project.find(params[:id])
   authorize @project

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Success' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    authorize @project

    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

end

app/views/projects/_form.html.erb
<%= form_for @project, :html => {:multipart => true} do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :key %>

  <p>File: <%= @project.image_name %></p>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  </div>
    <div class="field">
    <%= f.label :http_link %><br />
    <%= f.text_field :http_link %>
  </div>
  <div class="field">
    <%= f.label :tech_used %><br />
    <%= f.text_field :tech_used %>
  </div>
    <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<%= render 'layouts/nav' %>

<div id="apps" class="appsblock whiteblock block">
  <div class="block-container">
    <h1 class="title">Application Showcase</h1>
    <div class="description">My favorite applications I've worked on</div>
    <div class="apps">
      <div class="slider">
        <div class="navigation navigation-left">
          <i class="fa fa-chevron-left"></i>
        </div>
        <div class="navigation navigation-right">
          <i class="fa fa-chevron-right"></i>
        </div>

        <div class="rotator">
          <% @projects.each do |project| %>
            <% if project.name == "Grubly" %>
              <div class="slide active">
            <% else %>
              <div class="slide">
            <% end %>
              <div class="slide-wrapper">
                <div class="picture">
                  <%= image_tag("https://s3-us-west-2.amazonaws.com/dylangrant.us/#{project.key}") %>
                </div>
                <div class="container aleft">
                  <h1 class="title"><%= project.name %></h1>
                  <div class="description"><%= project.description %></div></br></br>
                  <div class="description">Tech Used: <em><%= project.tech_used %></em></div>
                  <div class="storebuttons">
                    <%= link_to "View Site", "http://#{project.http_link}", target: "blank", class: "storebutton" %>
                    <% if policy(project).show? %>
                      <%= link_to 'Admin', project_path(project), class: "storebutton" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>

      </div>
    </div>

    <% if policy(Project).create? %>
      <%= direct_upload_form_for @uploader do |f| %>
        <h2 id"AddNewProject">Add New Project</h2>
        <p><%= f.file_field :image %></p><br>
        <p><%= f.submit "Add Project" %></p>
      <% end %>
    <% end %>

  </div>
</div>

<%= render 'layouts/footer' %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<%= image_tag @project.image_url %>
<p>Published: <%= @project.published %></p>
<p>Link to site: <%= @project.http_link %></p>
<p>Technologies used: <%= @project.tech_used %></p>
<p>Description: <%= @project.description %></p>

<% if policy(@project).update? %>
  <%= link_to 'Edit', edit_project_path(@project) %><br><br>
<% end %>
<% if policy(@project).publish? && @project.published? == false %>
  <%= link_to 'Publish', project_path(@project, project: { published: true }), method: :put %><br><br>
<% end %>
<% if policy(@project).destroy? %>
  <%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' } %><br><br>
<% end %>



<!--
<h3>Comments: </h3>

<% @comments.each do |com| %>
  <tr id="<%= dom_id(com) %>-1">
    <td><%= com.author %></td></tr>
  <tr id="<%= dom_id(com) %>-2">
    <td><%= com.content %></td>
    <% if current_user.present? && current_user.editor? %>
      <td><%= link_to 'Destroy Comment', [@project, com], method: :delete %></td>
      <% if com.approved? == false %>
        <td><%= link_to 'Approve', post_comment_path(@project, com, comment: { approved: true }) , method: :put %></td>
      <% end %>
    <% end %>
  </tr>
<% end %>


<h4>Add a comment</h4>

<% if current_user.present? %>
  <%= render 'comments/form' %>
<% else %>
  <p>Login to comment</p>
<% end %>
<% if current_user.present? && current_user.editor? %>
  <%= link_to 'Edit', edit_project_path(@project) %> |
<% end %>
-->
<%= link_to 'Back', projects_path %>