config/routes.rb
MyPortfolio::Application.routes.draw do

  devise_for :users, path_names: { sign_in: "login",
                                   sign_out: "logout" },
                    controllers: { omniauth_callbacks: "omniauth_callbacks",
                                   sessions: "sessions" }

  resources :posts do
    resources :comments
  end

  resources :projects do
    resources :comments
  end

  resources :users

  root :to => 'about#index'

  get 'login' => 'devise/sessions#new'
  get 'about_me' => 'about#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body,
                  :title,
                  :created_at,
                  :published,
                  :published_at,
                  :content

  belongs_to :author, class_name: "User"

  has_many :comments, as: :commentable

  def publish!
    published = true
    save!
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @posts = policy_scope(Post)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find(params[:id])
    @commentable = @post
    @comments = @commentable.comments
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def create
    @post = Post.new(params[:post])
    authorize @post

    respond_to do |format|
      if @post.save
        current_user.posts << @post
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])
    authorize @post

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post

    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_path }
      format.json { head :no_content }
      format.js
    end
  end
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render 'layouts/nav' %>

<div class="block whiteblock blogblock">
  <div id="blog" class="block-container">
    <h1 class="title">Bloggin'</h1>
    <div class="description">Blog posts about technology</div>
    <div class="description">
      <% if policy(Post).create? %>
        <%= link_to 'New Post', new_post_path %>
      <% end %>
    </div>
    <% @posts.each do |post| %>
      <div class="post">
        <h2 class="title"><%= post.title %></h2>
        <div class="created"><%= l post.created_at %></div>
        <div class="post-body column-2"><%= post.body.html_safe %></div>
        <div class="more-link">
          <%= link_to 'Read More', post %>
        </div>
        <% if policy(post).update? %>
          <div class="basicbutton"><%= link_to 'Edit', edit_post_path(post) %></div>
        <% end %>
        <% if policy(post).destroy? %>
          <div class="basicbutton"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></div>
        <% end %>
        <% if policy(post).publish? && post.published? == false %>
          <div class="basicbutton"><%= link_to 'Publish', post_path(post, post: { published: true, published_at: Time.zone.now }), method: :put %></div>
          <% end %>
      </div>
    <% end %>
  </div>
</div>

<!-- <div class="block colorblock twitterblock">
  <div class="block-container">
    <div class="twitterlogo"><i class="fa fa-twitter fa-1x"></i></div>
    <div class="messages-container">
      <div class="message active">
        <div class="content">
          Future Twitter Feed.
        </div>
        <div class="author">@dgrant069 - 2013</div>
      </div>
    </div>
  </div>
</div> -->

<%= render 'layouts/footer' %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>

<div id="author">
  <p>Created on: <%= l @post.created_at %></p>
</div>

<!-- this needs to be fixed -->
<% @comments.each do |com| %>
  <tr id="<%= dom_id(com) %>-1">
    <td><%= com.author %></td></tr>
  <tr id="<%= dom_id(com) %>-2">
    <td><%= com.content %></td>
    <% if current_user.present? && current_user.editor? %>
      <td><%= link_to 'Destroy Comment', [@post, com], method: :delete %></td>
      <% if com.approved? == false %>
        <td><%= link_to 'Approve', post_comment_path(@post, com, comment: { approved: true }) , method: :put %></td>
      <% end %>
    <% end %>
  </tr>
<% end %>

<h4>Add a comment</h4>

<% if current_user.present? %>
  <%= render 'comments/form' %>
<% else %>
  <p>Login to comment</p>
<% end %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>