config/routes.rb
MyPortfolio::Application.routes.draw do

  devise_for :users, path_names: { sign_in: "login",
                                   sign_out: "logout" },
                    controllers: { omniauth_callbacks: "omniauth_callbacks",
                                   sessions: "sessions" }

  resources :posts do
    resources :comments
  end

  resources :projects do
    resources :comments
  end

  resources :users

  root :to => 'about#index'

  get 'login' => 'devise/sessions#new'
  get 'about_me' => 'about#index'

end

app/views/layouts/_G_Analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43567039-1', 'iltaen.com');
  ga('send', 'pageview');
</script>

app/views/layouts/_footer.html.erb
<div class="block colorblock footerblock">
  <a href="#home" class="copyright">&copy; Dylan Grant 2013</a>
</div>

app/views/layouts/_header.html.erb
<head>
  <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
  <%= stylesheet_link_tag "font-awesome", :media => "all" %>
  <%= stylesheet_link_tag "scaffolds", :media => "all" %>
  <%= stylesheet_link_tag "background-image", :media => "all" %>
  <%= stylesheet_link_tag "common_pages", :media => "all" %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application" %>
</head>

app/views/layouts/_login.html.erb
<div id="user_nav">
<!--  <% if user_signed_in? %>
    <li>Signed in as <%= current_user.email %></li>
    <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
    <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
  <% end %>-->
</div>

app/views/layouts/_nav.html.erb
<div class="mainmenu">
  <div class="menuwrapper">
    <div class="menulist">
      <ul class="items">
        <li class="menuitem">
          <%= link_to "PROJECTS", projects_path %>
          </li>
<!--           <li class="menuitem">
            <%= link_to "BLOG", posts_path %>
          </li>
 -->        </ul>
      </div>
        <%= link_to '<span class="companyname">Dylan Grant</span>'.html_safe, root_path, class: "logoblock" %>

        <div class="socialblock">
          <% if user_signed_in? %>
            <%= link_to "#{current_user.name}".html_safe, users_path(@user), class: "currentUser", title: "Profile" %>
            <%= link_to '<i class="fa fa-gear"></i>'.html_safe, destroy_user_session_path, method: :delete, class: "socialicon", title: "Sign Out" %>
          <% else %>
            <%= link_to '<i class="fa fa-facebook-square"></i>'.html_safe, user_omniauth_authorize_path(:facebook), class: "socialicon", title: "Facebook Login" %>
            <%= link_to '<i class="fa fa-twitter-square"></i>'.html_safe, user_omniauth_authorize_path(:twitter), class: "socialicon", title: "Twitter Login" %>
            <%= link_to '<i class="fa fa-google-plus-square"></i>'.html_safe, user_omniauth_authorize_path(:google_oauth2), class: "socialicon", title: "Google Login" %>
            <%= link_to '<i class="fa fa-linkedin-square"></i>'.html_safe, user_omniauth_authorize_path(:linkedin), class: "socialicon", title: "LinkedIn Login" %>
            <%= link_to '<i class="fa fa-gear"></i>'.html_safe, new_user_session_path, class: "socialicon", title: "Sign In" %>
          <% end %>
        </div>
    </div>
</div>

app/views/layouts/_old_head.html.erb
<!-- Meta Data -->
<%= csrf_meta_tags %>
<meta charset="utf-8">
<title>Dylan Wu Wei</title>
<meta name="Author" content="Dylan Grant">
<meta name="keywords" content="responsive html template, portfolio, creative, clean, minimal, white, mobile, develop, Dylan Grant">
<meta name="Description" content="">
<meta http-equiv="X-UA-Compatible" content="IE=8"/>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="Portfolio Home" content="Landing page for portfolio of work">

<!-- CSS -->
<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
<%= stylesheet_link_tag "application", :media => "all" %>

<!-- JS -->
<%= javascript_include_tag "application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render "layouts/header" %>
<body>
  <%= yield %>
</body>
</html>